name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t hashith/flask_api  .
      - name: Publish Image to docker hub
        run: docker push hashith/flask_api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: sudo docker pull hashith/flask_api:latest
      - name: Delete old container
        run: sudo docker rm -f react-container
      - name: Run Docker Container
        run: sudo docker run -d -p 5000:5000 --name react-container hashith/flask_api:latest
